// Copy for the bag (cart), checkout, order confirmation and order tracking pages.
export const bag = {
  eyebrow: "SUITOHOLIC ATELIER",
  title: "YOUR BAG",
  emptyTitle: "Your bag is empty",
  emptyText: "Discover bespoke shirts tailored to your exact measurements.",
  continueShoppingLabel: "CONTINUE SHOPPING",
  bespokeBadge: "BESPOKE CUSTOMIZED",
  standardSizeLabel: "Size",
  quantityLabel: "Qty",
  removeLabel: "Remove",
  unavailableText: "No longer available in this quantity — please update or remove.",
  summaryTitle: "ORDER SUMMARY",
  subtotalLabel: "Subtotal",
  customizationLabel: "Bespoke Tailoring",
  shippingLabel: "Shipping",
  freeLabel: "Complimentary",
  totalLabel: "Total",
  taxNote: "Inclusive of all taxes",
  checkoutLabel: "PROCEED TO CHECKOUT",
  assurances: ["30-Day Fit Guarantee", "Free Alterations", "Secure Checkout"],
  checkout: {
    title: "CHECKOUT",
    contactHeading: "CONTACT DETAILS",
    shippingHeading: "SHIPPING ADDRESS",
    paymentHeading: "PAYMENT METHOD",
    codLabel: "Cash on Delivery",
    codHint: "Pay when your tailored order arrives.",
    upiLabel: "UPI Transfer",
    upiHint: "Our concierge will share UPI payment details after confirming your measurements.",
    notesLabel: "Order notes (optional)",
    notesPlaceholder: "Fitting preferences, delivery instructions…",
    placeOrderLabel: "PLACE ORDER",
    placingLabel: "PLACING ORDER…",
    backToBagLabel: "BACK TO BAG",
  },
  confirmation: {
    eyebrow: "THANK YOU",
    title: "YOUR ORDER IS CONFIRMED",
    text: "A confirmation has been recorded for {email}. Our master tailors will begin crafting your pieces shortly.",
    orderNumberLabel: "Order Number",
    trackLabel: "TRACK THIS ORDER",
  },
  track: {
    eyebrow: "ORDER TRACKING",
    title: "TRACK YOUR ORDER",
    text: "Enter your order number and the email used at checkout.",
    orderNumberLabel: "Order number",
    emailLabel: "Email",
    submitLabel: "TRACK ORDER",
    statusHeading: "ORDER STATUS",
  },
};
