export const fabricsPage = {
  hero: {
    slides: [
      { title: "Atelier Textile Vault & Rolls", image: "/about_fabric_rolls.jpg" },
      { title: "Royal Emerald Velvet", image: "/fabric_roll_emerald_velvet.jpg" },
      { title: "Bordeaux Silk Jacquard", image: "/fabric_roll_bordeaux_silk.jpg" },
      { title: "Camel Cashmere Flannel", image: "/fabric_roll_camel_flannel.jpg" },
    ],
    prevAriaLabel: "Previous Fabric",
    nextAriaLabel: "Next Fabric",
  },
  categoryQuickRow: {
    items: [
      { id: "new-arrivals", name: "New Arrivals", image: "/fabric_cat_new_arrivals.jpg", isShopAll: false, link: "#swatches-studio" },
      { id: "season-special", name: "Season Special", image: "/fabric_cat_season_special.jpg", isShopAll: false, link: "#swatches-studio" },
      { id: "prints", name: "Prints", image: "/fabric_cat_prints.jpg", isShopAll: false, link: "#swatches-studio" },
      { id: "indigo-prints", name: "Indigo Prints", image: "/fabric_cat_indigo_prints.jpg", isShopAll: false, link: "#swatches-studio" },
      { id: "embroidery", name: "Embroidery", image: "/fabric_cat_embroidery.jpg", isShopAll: false, link: "#swatches-studio" },
      { id: "suits-sets", name: "Suits Sets", image: "/fabric_cat_suits_sets.jpg", isShopAll: false, link: "#swatches-studio" },
      { id: "dupatta", name: "Dupatta", image: "/fabric_cat_dupatta.jpg", isShopAll: false, link: "#swatches-studio" },
      { id: "coord-sets", name: "Co-ord Sets", image: "/fabric_cat_coord_sets.jpg", isShopAll: false, link: "#swatches-studio" },
      { id: "sherwani-fabric", name: "Sherwani Fabric", image: "/fabric_cat_sherwani_fabric.jpg", isShopAll: false, link: "#swatches-studio" },
      // isShopAll: renders the outlined arrow tile (image ignored) and resets the filter to "all".
      { id: "shop-all", name: "Shop all", image: "", isShopAll: true, link: "#swatches-studio" },
    ],
  },
  studio: {
    heading: "CURATED TEXTILE SWATCHES",
    subheading: "Inspect high-magnification weave density, laboratory parameters, and launch bespoke custom fitting.",
    // Tab ids must match a fabric `category` value; "all" shows every fabric.
    filterTabs: [
      { id: "all", label: "ALL ATELIER (14)" },
      { id: "stripes", label: "GIZA STRIPES" },
      { id: "linen", label: "NORMANDY LINEN" },
      { id: "wool", label: "MERINO & CASHMERE" },
      { id: "velvet_silk", label: "VELVET & SILK" },
      { id: "oxford_twill", label: "OXFORD & TWILL" },
    ],
    magnifyLabel: "Magnify Weave",
    specLabels: {
      composition: "Composition",
      yarnCount: "Yarn Count & Ply",
      weaveWeight: "Weave & Weight",
      breathability: "Breathability",
    },
    customizeLabel: "CUSTOMIZE SHIRT IN THIS FABRIC",
    // The fabric code is appended as ?fabric=<code>
    customizeLink: "/custom-shirt",
    requestSwatchLabel: "REQUEST PHYSICAL SWATCH SAMPLE",
    activeSelectionLabel: "ACTIVE SELECTION",
    inspectLabel: "INSPECT SWATCH",
  },
  // Complete master fabric collection. `category` must match a studio filter tab id.
  fabrics: [
    {
      id: "fabric-oxford-white",
      code: "OX-140-WH",
      name: "Optic White Royal Oxford",
      category: "oxford_twill",
      categoryLabel: "2-PLY ROYAL OXFORD",
      composition: "100% Long-Staple Egyptian Giza 140s Cotton",
      yarnCount: "140/2 Ne Compact Double-Twist",
      weave: "Distinctive 2x2 Micro-Basketweave",
      weight: "Year-Round Structured",
      gsm: "130 GSM",
      origin: "Nile Delta Harvest • Spun in Biella, Italy",
      opacity: "100% Solid Opaque",
      breathability: "High (4.8 / 5.0)",
      wrinkleResistance: "Natural Resilient Basketweave",
      image: "/fabric_roll_oxford_white.jpg",
      description:
        "Immaculate optic white 2-ply royal oxford with distinctive 2x2 micro-basketweave texture. Delivers exceptional drape, breathability, and timeless bespoke elegance.",
      shortInfo: "140/2 Ne Royal Oxford • 130 GSM",
      price: "Rs. 3,290 • BESPOKE FIT",
      bestFor: "Classic White Dress Shirts, Button-Down & Spread Collars, Business Formal",
      care: "Gentle Machine Wash at 30°C • Warm Steam Iron",
      accentColor: "#FAF8F5",
    },
    {
      id: "fabric-emerald-velvet",
      code: "VL-300-EM",
      name: "Royal Emerald Plush Velvet",
      category: "velvet_silk",
      categoryLabel: "ROYAL VELVET SUITING",
      composition: "100% Spun Micro-Velvet Silk Blend",
      yarnCount: "Plush High-Pile Filament Weave",
      weave: "Deep Pile Luminous Velvet Sheen",
      weight: "Winter Formal & Ceremonial",
      gsm: "300 GSM",
      origin: "Como Mills, Northern Italy",
      opacity: "100% Deep Opaque",
      breathability: "Medium (3.8 / 5.0)",
      wrinkleResistance: "Self-Recovering Plush Pile",
      image: "/fabric_roll_emerald_velvet.jpg",
      description:
        "Opulent royal emerald green velvet with deep multidimensional sheen and feather-soft hand feel. Engineered for evening statements, smoking jackets, and red-carpet ceremonial bandhgalas.",
      shortInfo: "300 GSM Silk-Touch Velvet • Plush Luster",
      price: "Rs. 4,490 • BESPOKE FIT",
      bestFor: "Ceremonial Bandhgalas, Evening Smoking Jackets, Red-Carpet Tuxedos",
      care: "Professional Dry Clean Only • Steam Only from Reverse",
      accentColor: "#0D382B",
    },
    {
      id: "fabric-waffle-sage",
      code: "PQ-120-SG",
      name: "Sage Botanical Waffle Piqué",
      category: "oxford_twill",
      categoryLabel: "3D HONEYCOMB PIQUÉ",
      composition: "100% Mercerized Egyptian Piqué Cotton",
      yarnCount: "120/2 Ne Double-Mercerized Piqué",
      weave: "3D Structured Honeycomb Micro-Knit",
      weight: "All-Season Breathable",
      gsm: "160 GSM",
      origin: "Giza Harvest • Mercerized in Biella",
      opacity: "100% Opaque",
      breathability: "Maximum Breathability (5.0 / 5.0)",
      wrinkleResistance: "Naturally Resilient Knit Stretch",
      image: "/fabric_roll_waffle_sage.jpg",
      description:
        "Earthy botanical sage green with a tactile 3D honeycomb waffle knit structure. Offers superior air circulation, subtle texture contrast, and refined smart-casual luxury.",
      shortInfo: "120/2 Ne 3D Honeycomb Knit • 160 GSM",
      price: "Rs. 3,390 • BESPOKE FIT",
      bestFor: "Luxury Polos, Mandarin Collar Overshirts, Weekend Resort Tailoring",
      care: "Machine Wash Cold 30°C • Flat Dry • Gentle Steam",
      accentColor: "#748574",
    },
    {
      id: "fabric-bordeaux-silk",
      code: "SJ-200-BX",
      name: "Bordeaux Ruby Silk Jacquard",
      category: "velvet_silk",
      categoryLabel: "CEREMONIAL SILK JACQUARD",
      composition: "100% Pure Mulberry Silk & Long-Staple Cotton",
      yarnCount: "200/2 Ne Filament Silk Weft",
      weave: "High-Luster Intricate Jacquard Luster",
      weight: "Evening Black-Tie Structured",
      gsm: "145 GSM",
      origin: "Lyon Historic Silk Ateliers, France",
      opacity: "100% Rich Opaque",
      breathability: "High (4.4 / 5.0)",
      wrinkleResistance: "Silken Memory Drape",
      image: "/fabric_roll_bordeaux_silk.jpg",
      description:
        "Deep bordeaux ruby jewel tone with luminous silk-touch luster. Woven on precision jacquard looms for black-tie dinner jackets, festive kurtas, and luxury bespoke vests.",
      shortInfo: "200/2 Ne High Luster Silk • 145 GSM",
      price: "Rs. 4,290 • BESPOKE FIT",
      bestFor: "Festive Silk Kurtas, Black-Tie Dinner Jackets, Contrast Waistcoats",
      care: "Professional Dry Clean Recommended • Cool Iron on Reverse",
      accentColor: "#581825",
    },
    {
      id: "fabric-charcoal-wool",
      code: "WL-140-CH",
      name: "Charcoal Super 140s Merino Wool",
      category: "wool",
      categoryLabel: "SUPER 140S MERINO WOOL",
      composition: "100% Australian Super 140s Worsted Merino Wool",
      yarnCount: "140s High-Twist 2-Ply Worsted",
      weave: "Fine Tailored Diagonal Micro-Twill",
      weight: "4-Season Suiting Classic",
      gsm: "260 GSM",
      origin: "Biella Wool Mills, Piedmont Italy",
      opacity: "100% Solid Opaque",
      breathability: "Excellent Thermal Regulation (4.9 / 5.0)",
      wrinkleResistance: "Ultra-High Natural Wool Creep Recovery",
      image: "/fabric_roll_charcoal_wool.jpg",
      description:
        "Sleek charcoal slate melange with superfine Australian merino wool fibers. Naturally fluid drape with impeccable crease recovery engineered for bespoke 2-piece and 3-piece suiting.",
      shortInfo: "Super 140s Australian Merino • 260 GSM",
      price: "Rs. 4,990 • BESPOKE FIT",
      bestFor: "Executive 2-Piece Suits, Gurkha Dress Trousers, Tailored Blazers",
      care: "Professional Dry Clean Only • Warm Press with Damp Cloth",
      accentColor: "#333333",
    },
    {
      id: "fabric-diamond-twill",
      code: "TW-904-BK",
      name: "Midnight Obsidian Diamond Twill",
      category: "oxford_twill",
      categoryLabel: "45° STEEP DIAMOND TWILL",
      composition: "100% Egyptian Giza 160s Combed Cotton",
      yarnCount: "160/2 Ne Ultra-Fine Spun",
      weave: "45° Steep Micro-Diamond Twill Weave",
      weight: "Lightweight Crisp Formal",
      gsm: "135 GSM",
      origin: "Alexandria Delta • Finished in Bergamo, Italy",
      opacity: "100% Jet Black Opaque",
      breathability: "High (4.7 / 5.0)",
      wrinkleResistance: "Crisp Resilient Twill Memory",
      image: "/fabric_roll_diamond_twill.jpg",
      description:
        "Intense midnight obsidian black with subtle diagonal micro-diamond luster. Soft yet structured, crafted for dramatic black formal dress shirts and tuxedo accents.",
      shortInfo: "160/2 Ne Egyptian Giza • 135 GSM",
      price: "Rs. 3,690 • BESPOKE FIT",
      bestFor: "Black Formal Dress Shirts, Mandarin Collars, Tuxedo Dinner Shirts",
      care: "Gentle Machine Wash Cold at 30°C • Steam Iron on Reverse",
      accentColor: "#111111",
    },
    {
      id: "fabric-iceblue-twill",
      code: "FT-120-BL",
      name: "Glacier Ice Blue French Twill",
      category: "oxford_twill",
      categoryLabel: "EXTRA-FINE FRENCH TWILL",
      composition: "100% Extra-Long Staple Combed Cotton",
      yarnCount: "120/2 Ne French Double-Spun",
      weave: "Subtle Diagonal French Micro-Twill",
      weight: "All-Season Sartorial",
      gsm: "125 GSM",
      origin: "Alsace Heritage Weaving Atelier, France",
      opacity: "100% Opaque",
      breathability: "Very High (4.8 / 5.0)",
      wrinkleResistance: "Smooth Silky Hand with Natural Drape",
      image: "/fabric_roll_iceblue_twill.jpg",
      description:
        "Serene glacier ice blue shade with smooth, micro-diagonal twill ribbing. Highly versatile luxury tone that pairs flawlessly with dark navy, charcoal, and beige suits.",
      shortInfo: "120/2 Ne French Twill • 125 GSM",
      price: "Rs. 3,490 • BESPOKE FIT",
      bestFor: "Boardroom Dress Shirts, Cutaway Collars, Double Cuff French Shirts",
      care: "Gentle Machine Wash at 30°C • Medium Steam Iron",
      accentColor: "#8FAEC6",
    },
    {
      id: "fabric-terracotta-slub",
      code: "LN-550-TC",
      name: "Tuscan Terracotta Heavy Slub Linen",
      category: "linen",
      categoryLabel: "PURE ARTISANAL SLUB LINEN",
      composition: "100% Pure Normandy Flax Linen",
      yarnCount: "55 Lea High-Texture Pure Flax",
      weave: "Tactile Cross-Slub Open Weave",
      weight: "Summer Breathable Heavy Slub",
      gsm: "165 GSM",
      origin: "Normandy Harvest • Woven in Tuscany, Italy",
      opacity: "Rich Semi-Opaque",
      breathability: "Maximum Breathability (5.0 / 5.0)",
      wrinkleResistance: "Distinguished Artisanal Linen Patina",
      image: "/fabric_roll_terracotta_linen.jpg",
      description:
        "Warm Tuscan terracotta clay tone with pronounced artisanal slub textures. Superior airflow and unmatched rustic elegance for resort tailoring and casual bespoke shirting.",
      shortInfo: "55 Lea Pure Normandy Flax • 165 GSM",
      price: "Rs. 3,890 • BESPOKE FIT",
      bestFor: "Relaxed Linen Shirts, Camp Collars, Safari Overshirts, Gurkha Pants",
      care: "Cold Hand Wash or Gentle Cycle • Line Dry • Steam Damp",
      accentColor: "#9E4732",
    },
    {
      id: "fabric-camel-flannel",
      code: "CS-180-CM",
      name: "Camel Tan Brushed Cashmere Flannel",
      category: "wool",
      categoryLabel: "BRUSHED CASHMERE & WOOL",
      composition: "90% Virgin Merino Wool, 10% Cashmere",
      yarnCount: "130s Superfine Brushed Worsted",
      weave: "Velvety Brushed Soft Flannel Weave",
      weight: "Autumn/Winter Sartorial",
      gsm: "280 GSM",
      origin: "Biella Luxury Mills, Italy",
      opacity: "100% Solid Opaque",
      breathability: "High Thermal Insulation (4.6 / 5.0)",
      wrinkleResistance: "Supreme Crease Recovery & Loft",
      image: "/fabric_roll_camel_flannel.jpg",
      description:
        "Warm sartorial camel tan with a velvety brushed cashmere-wool surface. Exquisite warmth and featherlight luxury tailored for autumn overshirts and unlined sport coats.",
      shortInfo: "Cashmere-Wool Blend • 280 GSM",
      price: "Rs. 5,290 • BESPOKE FIT",
      bestFor: "Winter Overshirts, Unstructured Sport Coats, Tailored Flannel Trousers",
      care: "Professional Dry Clean Only",
      accentColor: "#B88958",
    },
    {
      id: "fabric-cavalry-drill",
      code: "CD-280-OL",
      name: "Sartorial Olive Cavalry Drill",
      category: "oxford_twill",
      categoryLabel: "MILITARY CAVALRY DRILL",
      composition: "100% Heavy Structured Compact Drill Cotton",
      yarnCount: "Heavy-Twist 20/2 Drill Yarn",
      weave: "Steep Double-Drill Cavalry Weave",
      weight: "Heavyweight Structured",
      gsm: "270 GSM",
      origin: "Lancashire Heritage Cotton Mill, UK",
      opacity: "100% Rugged Opaque",
      breathability: "Medium-High (4.3 / 5.0)",
      wrinkleResistance: "Indestructible Heavyweight Structure",
      image: "/fabric_roll_cavalry_drill.jpg",
      description:
        "Heavyweight olive cavalry drill with prominent diagonal double-rib ridges. Robust, structured, and ideal for durable bespoke trousers, safari jackets, and workwear tailoring.",
      shortInfo: "Heavy Cavalry Double-Drill • 270 GSM",
      price: "Rs. 3,590 • BESPOKE FIT",
      bestFor: "Gurkha & Pleated Trousers, Safari Overshirts, Unlined Workwear Jackets",
      care: "Machine Wash at 30°C • Medium Iron",
      accentColor: "#555A3D",
    },
    {
      id: "fabric-sh403-rose",
      code: "SH-403-RS",
      name: "Blossom Rose Banker Stripe",
      category: "stripes",
      categoryLabel: "EGYPTIAN GIZA STRIPE",
      composition: "100% Egyptian Giza 140s Cotton (2-Ply)",
      yarnCount: "140/2 Ne Compact Spun",
      weave: "High-Density Fine Twill Weave",
      weight: "All-Season Sartorial",
      gsm: "120 GSM",
      origin: "Nile Delta Harvest • Spun in Italy",
      opacity: "100% Opaque",
      breathability: "High (4.8 / 5.0)",
      wrinkleResistance: "Natural Resilient Twill Drape",
      image: "/fabric_sh403_rose_stripe.jpg",
      description:
        "Soft blossom rose pink and optic white alternating candy stripes with fine diagonal twill ribbing. Provides an immaculate refined aesthetic for modern power dressing.",
      shortInfo: "140/2 Ne Egyptian Giza • 120 GSM",
      price: "Rs. 3,490 • BESPOKE FIT",
      bestFor: "Power Dressing Dress Shirts, Spread Collars, Tailored Suits",
      care: "Dry Clean or Gentle Machine Wash at 30°C • Warm Steam Iron",
      accentColor: "#D89A9E",
    },
    {
      id: "fabric-sh403-royal",
      code: "SH-403-BL",
      name: "Royal Bengal Banker Stripe",
      category: "stripes",
      categoryLabel: "EGYPTIAN GIZA STRIPE",
      composition: "100% Egyptian Giza 140s Cotton (2-Ply)",
      yarnCount: "140/2 Ne Compact Spun",
      weave: "High-Density Fine Twill Weave",
      weight: "All-Season Sartorial",
      gsm: "120 GSM",
      origin: "Nile Delta Harvest • Spun in Italy",
      opacity: "100% Opaque",
      breathability: "High (4.8 / 5.0)",
      wrinkleResistance: "Natural Resilient Twill Drape",
      image: "/fabric_sh403_royal_stripe.jpg",
      description:
        "Crisp royal blue and optic white alternating bengal stripes with micro-twill diagonal ribbing. Exceptional color vibrancy and soft wrinkle-resistant luster.",
      shortInfo: "140/2 Ne Egyptian Giza • 120 GSM",
      price: "Rs. 3,490 • BESPOKE FIT",
      bestFor: "Executive Boardroom Shirts, French Cuff Formals, Spread Collars",
      care: "Dry Clean or Gentle Machine Wash at 30°C • Warm Steam Iron",
      accentColor: "#2A5B8C",
    },
    {
      id: "fabric-st16974-terra",
      code: "ST-16974",
      name: "Terracotta & Chalk Stripe",
      category: "stripes",
      categoryLabel: "LONG-STAPLE STRIPE",
      composition: "100% Extra-Long Staple Luxury Cotton",
      yarnCount: "120/2 Ne Combed Long-Staple",
      weave: "Precision Vertical Bengal Weave",
      weight: "Lightweight Crisp",
      gsm: "115 GSM",
      origin: "Extra-Long Staple Combed Cotton",
      opacity: "100% Opaque",
      breathability: "Very High (4.9 / 5.0)",
      wrinkleResistance: "Smooth Compact Surface",
      image: "/fabric_st16974_terracotta_stripe.jpg",
      description:
        "Subtle dusty terracotta rose and chalk-white stripe with a smooth compact surface. Delivers a modern sartorial presence with effortless drape.",
      shortInfo: "120/2 Ne Long-Staple Cotton • 115 GSM",
      price: "Rs. 3,290 • BESPOKE FIT",
      bestFor: "Contemporary Sartorial Dress Shirts, Cutaway Collars, Tailored Blazers",
      care: "Gentle Machine Wash at 30°C • Medium Iron",
      accentColor: "#B25E4B",
    },
    {
      id: "fabric-superviola-sand",
      code: "V-13672/06",
      name: "Superviola Sand Flax Linen",
      category: "linen",
      categoryLabel: "SUPERVIOLA ARTISANAL LINEN",
      composition: "100% Pure Artisanal Normandy Flax Linen",
      yarnCount: "60 Lea Pure European Flax",
      weave: "Natural Slub Textural Cross-Weave",
      weight: "Summer Breathable Drape",
      gsm: "155 GSM",
      origin: "Normandy Flax Fields, France",
      opacity: "Semi-Opaque (Linen Texture)",
      breathability: "Maximum Breathability (5.0 / 5.0)",
      wrinkleResistance: "Characteristic Natural Linen Patina",
      image: "/fabric_superviola_sand_linen.jpg",
      description:
        "Undyed natural oatmeal sand tone with authentic linen slub texture. Air-permeable, cool to the skin, and develops a richer softer hand-feel with each wear.",
      shortInfo: "60 Lea Pure Normandy Flax • 155 GSM",
      price: "Rs. 3,790 • BESPOKE FIT",
      bestFor: "Resort Tailoring, Relaxed Bespoke Shirts, Mandarin Collars, Gurkha Trousers",
      care: "Hand Wash Cold or Gentle Cycle • Line Dry • Steam Iron while Damp",
      accentColor: "#D6C6B0",
    },
  ],
  showcaseGrid: {
    heading: "ATELIER TEXTILE ROLLS & DRAPES",
    subheading: "Curated genuine menswear weaves formatted for bespoke custom tailoring selection.",
    ctaLabel: "CUSTOMIZE NOW",
    ctaLink: "/custom-shirt",
    // isDetailedList: renders the centred info box with the subItems list instead of the bottom title pill.
    collections: [
      { id: "unstitched-suit", title: "Unstitched Suit", image: "/mens_fabric_unstitched_suit.jpg", isDetailedList: false, subItems: [] },
      { id: "embroidered", title: "Embroidered", image: "/mens_fabric_embroidered.jpg", isDetailedList: false, subItems: [] },
      { id: "printed", title: "Printed", image: "/mens_fabric_printed.jpg", isDetailedList: false, subItems: [] },
      {
        id: "imported-plain",
        title: "Imported Plain",
        image: "/mens_fabric_imported_plain.jpg",
        isDetailedList: true,
        subItems: [
          { label: "Banana Lycra" },
          { label: "Moss Crepe/ Summer Lycra" },
          { label: "Luxury Velvet" },
          { label: "Milano Satin" },
          { label: "Dust Satin" },
        ],
      },
    ],
  },
  editorial: {
    eyebrow: "SARTORIAL PRECISION",
    headingLine1: "INDIVIDUALLY DRAFTED & HAND-CUT",
    headingLine2: "ON BESPOKE PATTERNS.",
    body: "Before a single needle touches your chosen cloth, every meter is rested for 48 hours to neutralize weave tension, inspected under daylight lamps, and hand-chalked to your exact anatomical posture.",
    stats: [
      { value: "140/2 Ne", label: "Two-Fold Giza Yarn" },
      { value: "100%", label: "Pure Plant Fibers" },
      { value: "0%", label: "Shrinkage Post-Wash" },
    ],
    image: "/atelier_bespoke_editorial_bg.jpg",
    imageAlt: "Suitoholic Bespoke Cutting Table with Pure Linen and Tailor Tools",
  },
  zoomModal: {
    closeAriaLabel: "Close Magnifier",
    magnificationBadge: "MAGNIFICATION: 3.5X HIGH-DEFINITION WEAVE",
    configuratorLabel: "SELECT IN CONFIGURATOR →",
  },
  swatchRequest: {
    eyebrow: "ATELIER CONCIERGE",
    heading: "REQUEST SAMPLE SWATCH",
    closeAriaLabel: "Close Modal",
    introBefore: "Receive a complimentary tactile swatch card of",
    introAfter: "delivered to your doorstep.",
    nameLabel: "Full Name",
    namePlaceholder: "e.g. Lord Alexander Wright",
    addressLabel: "Delivery Address",
    addressPlaceholder: "Apartment, Street Address, City, Postal Code",
    phoneLabel: "Phone Number (For Courier)",
    phonePlaceholder: "+91 98765 43210",
    emailLabel: "Email (Optional)",
    emailPlaceholder: "you@example.com",
    submitLabel: "DISPATCH SWATCH SAMPLE",
    submittingLabel: "DISPATCHING…",
    contactRequiredMessage: "Please provide a phone number or email so we can reach you.",
    errorMessage: "We couldn't submit your swatch request. Please try again.",
    successHeading: "Sample Box Dispatched",
    successTextBefore: "Your physical swatch of",
    successTextAfter: "has been queued for express courier dispatch.",
  },
};
