export const productPage = {
  backLabel: "BACK TO CATALOG",
  galleryTabLabel: "HIGH-RES GALLERY",
  mannequinTabLabel: "3D MANNEQUIN FIT",
  zoomHint: "HOVER TO ZOOM",
  badges: [
    { icon: "shield", title: "100% Giza Cotton", subtitle: "140s 2-Ply Fine Weave" },
    { icon: "scissors", title: "Hand Cut & Sewn", subtitle: "Master Shirtmakers" },
    { icon: "refresh", title: "30-Day Fit Guarantee", subtitle: "Free Alterations" },
  ],
  brandEyebrow: "SUITOHOLIC BESPOKE ATELIER",
  reviewsSuffix: "Bespoke Client Reviews",
  taxNote: "(Inclusive of all taxes & complimentary shipping)",
  colorwaysLabel: "AVAILABLE FABRIC COLORWAYS",
  addToBagLabel: "ADD TO BAG",
  addToBagHint: "6 STEPS →",
  buyNowLabel: "BUY NOW",
  outOfStockLabel: "OUT OF STOCK",
  lowStockTemplate: "Only {stock} left in stock",
  addedToBagTemplate: "{name} ({details}) ADDED TO BAG!",
  viewBagLabel: "VIEW BAG",
  specsHeading: "PRODUCT SPECIFICATIONS",
  specLabels: {
    fabric: "Fabric Composition:",
    threadCount: "Thread Count / Weave:",
    collar: "Collar Structure:",
    cuff: "Cuff Construction:",
  },
  descriptionHeading: "DESCRIPTION",
  macroEyebrow: "MACRO DETAIL GALLERY",
  macroTitle: "Uncompromising Fabric & Finish",
  macroCards: [
    {
      image: "/detail_fabric_macro.jpg",
      alt: "140s Giza Cotton Macro Texture",
      eyebrow: "WEAVE & TEXTURE",
      title: "140s 2-Ply Fine Twill",
      text: "Double-ply long-staple Egyptian cotton woven for silky touch, natural luster, and crisp drape.",
      contain: false,
    },
    {
      image: "/detail_cuff_collar.jpg",
      alt: "Collar and Cuff Craftsmanship",
      eyebrow: "COLLAR & CUFF",
      title: "Hand-Cut English Spread",
      text: "German fused interlining ensures permanent collar roll with removable brass stays and convertible French cuffs.",
      contain: false,
    },
    {
      image: "/custom_fit_shirt_hq.png",
      alt: "3D Bespoke Tailored Silhouette",
      eyebrow: "SARTORIAL FIT",
      title: "Anatomical 3D Morphing",
      text: "Precision pattern cut according to your individual chest, waist, and height proportions.",
      contain: true,
    },
  ],
  completeLookEyebrow: "SARTORIAL STYLING",
  completeLookTitle: "Complete The Bespoke Look",
  completeLookSubtitle: "Handpicked items to pair with",
  addToOutfitLabel: "+ ADD TO OUTFIT",
  addedToOutfitTemplate: "{name} ADDED TO YOUR OUTFIT!",
  moreEyebrow: "CURATED SELECTION",
  moreTitle: "More Bespoke Shirt Colorways",
  viewAllLabel: "VIEW ALL CATALOG",
  notFoundTitle: "This piece is no longer available",
  notFoundCta: "BROWSE THE CATALOG",
};
