export const shopPage = {
  eyebrowLeft: "SUITOHOLIC ATELIER",
  eyebrowRight: "BESPOKE COLLECTION",
  title: "THE SHIRT ATELIER",
  allPillLabel: "ALL SHIRTS",
  allSidebarLabel: "ALL SHIRTS & PRODUCTS",
  allCategoryName: "ALL SHIRTS",
  collectionsHeading: "COLLECTIONS",
  resetLabel: "RESET",
  filterHeading: "FILTER BY",
  fabricFilterLabel: "FABRIC",
  priceFilterLabel: "PRICE RANGE",
  priceRanges: [
    { label: "Under ₹ 2,500", min: 0, max: 2499 },
    { label: "₹ 2,500 – ₹ 4,999", min: 2500, max: 4999 },
    { label: "₹ 5,000 – ₹ 9,999", min: 5000, max: 9999 },
    { label: "₹ 10,000 & above", min: 10000, max: 10000000 },
  ],
  resetAllLabel: "RESET ALL FILTERS",
  itemsAvailableLabel: "Items Available",
  sortLabel: "SORT BY:",
  sortOptions: {
    featured: "NEW ARRIVALS",
    priceAsc: "PRICE: LOW TO HIGH",
    priceDesc: "PRICE: HIGH TO LOW",
    rating: "TOP RATED",
  },
  customizeLabel: "CUSTOMIZE",
  emptyText: "No pieces match these filters yet.",
  loadingText: "Loading Shop...",
};
